# Generated by Django 3.0.3 on 2020-06-07 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('comp_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=7)),
                ('start_date', models.CharField(max_length=200)),
                ('end_date', models.IntegerField()),
                ('expired', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='comp_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='raffle.Competition'),
            preserve_default=False,
        ),
    ]
