# Generated by Django 3.0.3 on 2020-06-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0002_auto_20200607_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateField(),
        ),
    ]
