# Generated by Django 3.0.3 on 2020-06-07 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0004_auto_20200607_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='expired',
        ),
    ]
